apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
  labels:
    kubernetes.io/metadata.name: dtk-light
  name: dtk-light
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: dtk-light
  name: dtk-light
  namespace: dtk-light
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: dtk-light
  name: dtk-light
  namespace: dtk-light
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    type: Git
    git:
      uri: https://github.com/enriquebelarte/driver-toolkit-nokvc
    contextDir: .
  strategy:
    type: Docker                      
    dockerStrategy:
      #dockerfilePath: Dockerfile-silly-kmod.multistage
      dockerfilePath: Dockerfile-silly-kmod-ocp-release.multistage
      buildArgs:
        - name: KMODVER
          value: DEMO
        - name: KERNEL_VERSION
          value: "4.18.0-305.34.2.el8_4"
        - name: RHEL_VERSION
          value: "8.4"
  output:
    to:
      kind: ImageStreamTag
      name: dtk-light:demo
